version: 2
parallelism: 5
jobs:
  build-env:
    docker:
      - image: kudo/ubuntu-nonroot:18.04
        user: ubuntu
        environment:
          DEBIAN_FRONTEND: noninteractive
          TZ: UTC

    working_directory: ~/v8-android-buildscripts
    steps:
      - run:
          name: Setup Ubuntu environment
          command: |
            sudo ln -fs /usr/share/zoneinfo/UTC /etc/localtime
            sudo apt-get update
            sudo apt-get upgrade -y
            sudo apt-get install -y apt-utils sudo lsb-core git python nodejs npm wget openjdk-8-jre openjdk-8-jdk

      - checkout

      - run:
          name: Export settings from npm package
          command: |
            npm run export_npm_env

      - run:
          name: Setup V8 build environment
          command: |
            scripts/setup.sh -r ${V8_VERSION} android
            sudo apt-get install -y libatomic1-i386-cross && sudo sh -c 'echo "/usr/i686-linux-gnu/lib" >> /etc/ld.so.conf.d/i386-linux-gnu.conf' && sudo ldconfig

      - run:
          name: Patch V8
          command: |
            scripts/patch.sh android

  build-V8-arm:
    docker:
      - image: kudo/ubuntu-nonroot:18.04
        user: ubuntu
        environment:
          DEBIAN_FRONTEND: noninteractive
          TZ: UTC

    working_directory: ~/v8-android-buildscripts
    steps:
      - run:
          name: Build V8 arm
          command: |
            NO_INTL=1 scripts/build_arm.sh android

  build-V8-arm64:
    docker:
      - image: kudo/ubuntu-nonroot:18.04
        user: ubuntu
        environment:
          DEBIAN_FRONTEND: noninteractive
          TZ: UTC

    working_directory: ~/v8-android-buildscripts
    steps:
      - run:
          name: Build V8 arm64
          command: |
            NO_INTL=1 scripts/build_arm64.sh android

  build-V8-x64:
    docker:
      - image: kudo/ubuntu-nonroot:18.04
        user: ubuntu
        environment:
          DEBIAN_FRONTEND: noninteractive
          TZ: UTC

    working_directory: ~/v8-android-buildscripts
    steps:
      - run:
          name: Build V8 x64
          command: |
            NO_INTL=1 scripts/build_x64.sh android

  build-V8-x86:
    docker:
      - image: kudo/ubuntu-nonroot:18.04
        user: ubuntu
        environment:
          DEBIAN_FRONTEND: noninteractive
          TZ: UTC

    working_directory: ~/v8-android-buildscripts
    steps:
      - run:
          name: Build V8 x86
          command: |
            NO_INTL=1 scripts/build_x86.sh android


  archive:
    docker:
      - image: kudo/ubuntu-nonroot:18.04
        user: ubuntu
        environment:
          DEBIAN_FRONTEND: noninteractive
          TZ: UTC

    working_directory: ~/v8-android-buildscripts
    steps:
      - run:
          name: Archive
          command: |
            NO_INTL=1 scripts/archive.sh android
            tar cvfz dist.tgz dist

      - store_artifacts:
          path: dist.tgz

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-env
      - build-V8-arm:
          requires:
            - build-env
      - build-V8-arm64:
          requires:
            - build-env
      - build-V8-x64:
          requires:
            - build-env
      - build-V8-x86:
          requires:
            - build-env
      - archive:
          requires:
            - build-V8-arm
            - build-V8-arm64
            - build-V8-x64
            - build-V8-x86
